// <auto-generated />
using System;
using MagicVilla_APICURSO.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_APICURSO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_APICURSO.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = " ",
                            Detalle = "Detalle Paraiso",
                            FechaActualizacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1871),
                            FechaCreacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1861),
                            ImagenUrl = " ",
                            MetrosCuadrados = 255,
                            Nombre = "Villa Paraiso",
                            Ocupantes = 5,
                            Tarifa = 300.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = " ",
                            Detalle = "Detalle Selva",
                            FechaActualizacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1874),
                            FechaCreacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1873),
                            ImagenUrl = " ",
                            MetrosCuadrados = 255,
                            Nombre = "Villa Selva",
                            Ocupantes = 2,
                            Tarifa = 350.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = " ",
                            Detalle = "Detalle Tropical",
                            FechaActualizacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1876),
                            FechaCreacion = new DateTime(2024, 5, 31, 19, 2, 39, 219, DateTimeKind.Local).AddTicks(1875),
                            ImagenUrl = " ",
                            MetrosCuadrados = 500,
                            Nombre = "Villa Tropical",
                            Ocupantes = 6,
                            Tarifa = 850.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
